const langs = [
  {
    name: "hr",
    image: require("../images/langImages/hr.png"),
    homeText: "POČETNA",
    infoText: "INFORMACIJE",
    settingsText: "POSTAVKE",
    busStation: "- Autobusna stanica",
    findNearestStop: "- Pronađi najbližu stanicu",
    showAllRoutes: "- Prikaži sve autobusne rute",
    toggleMapStyle: "- Promjeni izgled karte",
    route: "- Ruta (klik za prikaz rute)",
    language: "Jezik",
    search: "Pronađi ulicu...",
    stopDetails: "VIŠE DETALJA",
    distanceFromYourLocation: "Udaljenost od Vaše lokacije:",
    nearestStopAtDesiredLocation: "Udaljenost najbliže stanice od lokacije:",
    allRoutes: "Sve linije",
    activeRoute: "Aktivna ruta:",
  },
  {
    name: "gb",
    image: require("../images/langImages/gb.png"),
    homeText: "HOME",
    infoText: "INFO",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
    search: "Find a street...",
    stopDetails: "MORE DETAILS",
    distanceFromYourLocation: "Distance from your location:",
    nearestStopAtDesiredLocation: "Nearest bus stop at desired location:",
    allRoutes: "All routes",
    activeRoute: "Active route:",
  },
  {
    name: "de",
    image: require("../images/langImages/de.png"),
    homeText: "STARTSEITE",
    infoText: "INFORMATIONEN",
    settingsText: "EINSTELLUNGEN",
    busStation: "- Bushaltestelle",
    findNearestStop: "- Nächste Bushaltestelle finden",
    showAllRoutes: "- Alle Routen anzeigen",
    toggleMapStyle: "- Kartenstil umschalten",
    route: "- Route (zum Anzeigen klicken)",
    language: "Sprache",
    search: "Straße finden...",
    stopDetails: "MEHR DETAILS",
    distanceFromYourLocation: "Entfernung von Ihrem Standort:",
    nearestStopAtDesiredLocation: "Nächste Bushaltestelle am gewünschten Ort:",
    allRoutes: "Alle routen",
    activeRoute: "Aktive route:",
  },

  {
    name: "it",
    image: require("../images/langImages/it.png"),
    homeText: "INIZIO",
    infoText: "INFORMAZIONI",
    settingsText: "IMPOSTAZIONI",
    busStation: "- Stazione degli autobus",
    findNearestStop: "- Trova la fermata più vicina",
    showAllRoutes: "- Mostra tutte le rotte",
    toggleMapStyle: "- Cambia stile della mappa",
    route: "- Rotta (clicca per visualizzare la rotta)",
    language: "Lingua",
    search: "Trova una strada...",
    stopDetails: "MAGGIORI DETTAGLI",
    distanceFromYourLocation: "Distanza dalla tua posizione:",
    nearestStopAtDesiredLocation:
      "Fermata dell'autobus più vicina alla posizione desiderata:",
    allRoutes: "Tutte le rotte",
    activeRoute: "Rotta attiva:",
  },

  {
    name: "fr",
    image: require("../images/langImages/fr.png"),
    homeText: "ACCUEIL",
    infoText: "INFORMATIONS",
    settingsText: "PARAMÈTRES",
    busStation: "- Station de bus",
    findNearestStop: "- Trouver l'arrêt de bus le plus proche",
    showAllRoutes: "- Afficher toutes les lignes",
    toggleMapStyle: "- Basculer le style de la carte",
    route: "- Itinéraire (cliquer pour afficher l'itinéraire)",
    language: "Langue",
    search: "Trouver une rue...",
    stopDetails: "PLUS DE DÉTAILS",
    distanceFromYourLocation: "Distance depuis votre position:",
    nearestStopAtDesiredLocation:
      "Arrêt de bus le plus proche à l'endroit souhaité:",
    allRoutes: "Toutes les lignes",
    activeRoute: "Route active:",
  },

  {
    name: "es",
    image: require("../images/langImages/es.png"),
    homeText: "INICIO",
    infoText: "INFORMACIÓN",
    settingsText: "CONFIGURACIÓN",
    busStation: "- Estación de autobuses",
    findNearestStop: "- Encontrar la parada de autobús más cercana",
    showAllRoutes: "- Mostrar todas las rutas",
    toggleMapStyle: "- Cambiar el estilo del mapa",
    route: "- Ruta (haga clic para mostrar la ruta)",
    language: "Idioma",
    search: "Encontrar una calle...",
    stopDetails: "MÁS DETALLES",
    distanceFromYourLocation: "Distancia desde su ubicación:",
    nearestStopAtDesiredLocation:
      "Parada de autobús más cercana a la ubicación deseada:",
    allRoutes: "Todas las rutas",
    activeRoute: "Ruta activa:",
  },
];

export default langs;
