const langs = [
  {
    name: "hr",
    image: require("../images/langImages/hr.png"),
    homeText: "POČETNA",
    infoText: "INFORMACIJE",
    settingsText: "POSTAVKE",
    busStation: "- Autobusna stanica",
    findNearestStop: "- Pronađi najbližu stanicu",
    showAllRoutes: "- Prikaži sve autobusne rute",
    toggleMapStyle: "- Promjeni izgled karte",
    route: "- Ruta (klik za prikaz rute)",
    language: "Jezik",
    search: "Pronađi ulicu...",
    stopDetails: "VIŠE DETALJA",
    distanceFromYourLocation: "Udaljenost od Vaše lokacije:",
    nearestStopAtDesiredLocation: "Udaljenost najbliže stanice od lokacije:",
    allRoutes: "Sve linije",
    activeRoute: "Aktivna ruta:",
    errorStreet: "Nije moguće pronaći ulicu! Pokušajte ponovo.",
    showPath: "Pokaži put",
    start: "Početak",
    finish: "Završetak",
    radius: "Smanjenje radijusa može povećati performanse",
    adequateRoute: "Ne mogu pronaći odgovarajući put!",
    busRoute: "Autobusna linija",
    numStops: "Broj stanica",
    routePlanner: "Planiraj svoj put",
    find: "PRONAĐI",
    curStation: "Trenutna stanica #:",
    enter: "Uđite u bus sa oznakom:",
  },
  {
    name: "gb",
    image: require("../images/langImages/gb.png"),
    homeText: "HOME",
    infoText: "INFO",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
    search: "Find a street...",
    stopDetails: "MORE DETAILS",
    distanceFromYourLocation: "Distance from your location:",
    nearestStopAtDesiredLocation: "Nearest bus stop at desired location:",
    allRoutes: "All routes",
    activeRoute: "Active route:",
    errorStreet: "Could not find the street! Try again.",
    showPath: "Show path",
    start: "Start",
    finish: "Finish",
    radius: "Lowering radius may increase performance",
    adequateRoute: "Cannot find adequate route!",
    busRoute: "Bus route",
    numStops: "Num. of stops",
    routePlanner: "Plan your route",
    find: "FIND",
    curStation: "Current station #:",
    enter: "Board the bus with the sign:",
  },
  {
    name: "de",
    image: require("../images/langImages/de.png"),
    homeText: "STARTSEITE",
    infoText: "INFORMATIONEN",
    settingsText: "EINSTELLUNGEN",
    busStation: "- Bushaltestelle",
    findNearestStop: "- Nächste Bushaltestelle finden",
    showAllRoutes: "- Alle Routen anzeigen",
    toggleMapStyle: "- Kartenstil umschalten",
    route: "- Route (zum Anzeigen klicken)",
    language: "Sprache",
    search: "Straße finden...",
    stopDetails: "MEHR DETAILS",
    distanceFromYourLocation: "Entfernung von Ihrem Standort:",
    nearestStopAtDesiredLocation: "Nächste Bushaltestelle am gewünschten Ort:",
    allRoutes: "Alle routen",
    activeRoute: "Aktive route:",
    errorStreet: "Straße nicht gefunden! Versuchen Sie es erneut.",
    showPath: "Weg anzeigen",
    start: "Start",
    finish: "Ziel",
    radius: "Eine Verringerung des Radius kann die Leistung erhöhen",
    adequateRoute: "Angemessene Route konnte nicht gefunden werden!",
    busRoute: "Buslinie",
    numStops: "Anzahl haltestellen",
    routePlanner: "Plane deine Route",
    find: "FINDEN",
    curStation: "Aktuelle Station #:",
    enter: "Steigen Sie in den Bus mit dem Schild ein:",
  },

  {
    name: "it",
    image: require("../images/langImages/it.png"),
    homeText: "INIZIO",
    infoText: "INFORMAZIONI",
    settingsText: "IMPOSTAZIONI",
    busStation: "- Stazione degli autobus",
    findNearestStop: "- Trova la fermata più vicina",
    showAllRoutes: "- Mostra tutte le rotte",
    toggleMapStyle: "- Cambia stile della mappa",
    route: "- Rotta (clicca per visualizzare la rotta)",
    language: "Lingua",
    search: "Trova una strada...",
    stopDetails: "MAGGIORI DETTAGLI",
    distanceFromYourLocation: "Distanza dalla tua posizione:",
    nearestStopAtDesiredLocation:
      "Fermata dell'autobus più vicina alla posizione desiderata:",
    allRoutes: "Tutte le rotte",
    activeRoute: "Rotta attiva:",
    errorStreet: "Impossibile trovare la strada! Riprova.",
    showPath: "Mostra percorso",
    start: "Inizio",
    finish: "Fine",
    radius: "Ridurre il raggio potrebbe aumentare le prestazioni",
    adequateRoute: "Impossibile trovare un percorso adeguato!",
    busRoute: "Percorso autobus",
    numStops: "Num. fermate",
    routePlanner: "Pianifica il tuo percorso",
    find: "TROVA",
    curStation: "Stazione attuale #:",
    enter: "Salite sull'autobus con il segno:",
  },

  {
    name: "fr",
    image: require("../images/langImages/fr.png"),
    homeText: "ACCUEIL",
    infoText: "INFORMATIONS",
    settingsText: "PARAMÈTRES",
    busStation: "- Station de bus",
    findNearestStop: "- Trouver l'arrêt de bus le plus proche",
    showAllRoutes: "- Afficher toutes les lignes",
    toggleMapStyle: "- Basculer le style de la carte",
    route: "- Itinéraire (cliquer pour afficher l'itinéraire)",
    language: "Langue",
    search: "Trouver une rue...",
    stopDetails: "PLUS DE DÉTAILS",
    distanceFromYourLocation: "Distance depuis votre position:",
    nearestStopAtDesiredLocation:
      "Arrêt de bus le plus proche à l'endroit souhaité:",
    allRoutes: "Toutes les lignes",
    activeRoute: "Route active:",
    errorStreet: "Impossible de trouver la rue ! Réessayez.",
    showPath: "Afficher le chemin",
    start: "Début",
    finish: "Fin",
    radius: "Réduire le rayon peut augmenter les performances",
    adequateRoute: "Impossible de trouver un itinéraire adéquat !",
    busRoute: "Ligne de bus",
    numStops: "Nb. d'arrêts",
    routePlanner: "Planifiez votre itinéraire",
    find: "TROUVER",
    curStation: "Station actuelle # :",
    enter: "Montez dans le bus avec le panneau :",
  },

  {
    name: "es",
    image: require("../images/langImages/es.png"),
    homeText: "INICIO",
    infoText: "INFORMACIÓN",
    settingsText: "CONFIGURACIÓN",
    busStation: "- Estación de autobuses",
    findNearestStop: "- Encontrar la parada de autobús más cercana",
    showAllRoutes: "- Mostrar todas las rutas",
    toggleMapStyle: "- Cambiar el estilo del mapa",
    route: "- Ruta (haga clic para mostrar la ruta)",
    language: "Idioma",
    search: "Encontrar una calle...",
    stopDetails: "MÁS DETALLES",
    distanceFromYourLocation: "Distancia desde su ubicación:",
    nearestStopAtDesiredLocation:
      "Parada de autobús más cercana a la ubicación deseada:",
    allRoutes: "Todas las rutas",
    activeRoute: "Ruta activa:",
    errorStreet: "¡No se pudo encontrar la calle! Inténtalo de nuevo.",
    showPath: "Mostrar ruta",
    start: "Comienzo",
    finish: "Fin",
    radius: "Reducir el radio puede aumentar el rendimiento",
    adequateRoute: "¡No se puede encontrar una ruta adecuada!",
    busRoute: "Ruta de autobús",
    numStops: "Num. de paradas",
    routePlanner: "Planifica tu ruta",
    find: "ENCONTRAR",
    curStation: "Estación actual #:",
    enter: "Suba al autobús con el letrero:",
  },
];

export default langs;
