const langs = [
  {
    name: "hr",
    image: require("../images/langImages/hr.png"),
    homeText: "POČETNA",
    infoText: "INFORMACIJE",
    settingsText: "POSTAVKE",
    busStation: "- Autobusna stanica",
    findNearestStop: "- Pronađi najbližu stanicu",
    showAllRoutes: "- Prikaži sve autobusne rute",
    toggleMapStyle: "- Promjeni izgled karte",
    route: "- Ruta (klik za prikaz rute)",
    language: "Jezik",
  },
  {
    name: "gb",
    image: require("../images/langImages/gb.png"),
    homeText: "HOME",
    infoText: "INFO",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
  },
  {
    name: "de",
    image: require("../images/langImages/de.png"),
    homeText: "HOME - DE",
    infoText: "INFO - DE",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
  },

  {
    name: "it",
    image: require("../images/langImages/it.png"),
    homeText: "HOME - IT",
    infoText: "INFO - IT",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
  },

  {
    name: "fr",
    image: require("../images/langImages/fr.png"),
    homeText: "HOME - FR",
    infoText: "INFO - FR",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
  },

  {
    name: "es",
    image: require("../images/langImages/es.png"),
    homeText: "HOME - ES",
    infoText: "INFO - ES",
    settingsText: "SETTINGS",
    busStation: "- Bus station",
    findNearestStop: "- Find nearest bus station",
    showAllRoutes: "- Show all routes",
    toggleMapStyle: "- Toggle map style",
    route: "- Route (click to show the route)",
    language: "Language",
  },
];

export default langs;
